In [2]:
# 지도학습, 분류 -> 붓꽃의 품종을 정확하게 분류한 데이터
# 클래스(class) -> 출력될 수 있는 값(붓꽃의 종류) 
# 레이블(label) -> 붓꽃의 품종

In [5]:
# dataset 불러오기
from sklearn.datasets import load_iris
iris_dataset = load_iris()

In [25]:
# dataset 확인
print("iris _dataset의 키:\n", iris_dataset.keys())

# target 확인
# 0:setosa, 1:versicolor, 2:virginica
print("target의 이름:\n", iris_dataset['target_names'])
print("target의 타입:\n", type(iris_dataset['target']))
print("target의 크기:\n", iris_dataset['target'].shape)
print("target: \n", iris_dataset['target'])

# feature 확인
print("feature의 이름:\n", iris_dataset['feature_names'])      

# data 확인
print("data의 타입:\n", type(iris_dataset['data']))
print("data의 크기:\n", iris_dataset['data'].shape)
print("data의 처음 5개 행:\n", iris_dataset['data'][:5])

iris _dataset의 키:
 dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])
target의 이름:
 ['setosa' 'versicolor' 'virginica']
target의 타입:
 <class 'numpy.ndarray'>
target의 크기:
 (150,)
target: 
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
feature의 이름:
 ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
data의 타입:
 <class 'numpy.ndarray'>
data의 크기:
 (150, 4)
data의 처음 5개 행:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [36]:
# train, test data 나누기
# random_state = 0 -> 난수를 항상 고정된 값으로 입력하여 항상 결과가 같음
# X_train: 전체 데이터의 75%, X_test: 전체 데이터의 25%
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris_dataset['data'], iris_dataset['target'], random_state=0)

print("X_train 크기:", X_train.shape)
print("y_train 크기:", y_train.shape)
print("X_test 크기:", X_test.shape)
print("y_test 크기:", y_test.shape)

X_train 크기: (112, 4)
y_train 크기: (112,)
X_test 크기: (38, 4)
y_test 크기: (38,)


### K-Nearest Neighbors(KNN)

In [52]:
# KNN에서 k는 가장 가까운 이웃 '하나'가 아니라 훈련 데이터에서 새로운 데이터 포인트에 가장 가까운 K개의 이웃을 찾는다는 듯
# 그 후, 다음 이웃들의 클래스 중 빈도가 가장 높은 클래스를 예측값으로 사용

In [53]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=1)

In [57]:
# 모델 만들기
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=1)

In [56]:
import numpy as np
# 꽃받침: 5cm, 폭: 2.9cm, 꽃잎: 1cm, 폭: 0.2cm
X_new = np.array([[5, 2.9, 1, 0.2]])
print ("X_new.shape:", X_new. shape)

X_new.shape: (1, 4)


In [63]:
# 예측하기
prediction = knn.predict(X_new)
print("예측:", prediction)
print("예측한 타깃의 이름:", iris_dataset['target_names'][prediction])

예측: [0]
예측한 타깃의 이름: ['setosa']


In [69]:
# 평가하기
y_pred = knn.predict(X_test)
print("테스트 세트에 대한 예측값:\n", y_pred)
# 테스트 정확도 출력하기
print("테스트 세트의 정확도: {:.2f}".format(np.mean(y_pred==y_test)))
print("테스트 세트의 정확도: {:.2f}".format(knn.score(X_test, y_test)))

테스트 세트에 대한 예측값:
 [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2]
테스트 세트의 정확도: 0.97
테스트 세트의 정확도: 0.97
